name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Set Public Key
        run: echo "TF_VAR_public_key=${{ secrets.SSH_PUBLIC_KEY }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Fetch EC2 Public IP
        run: |
          export EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)
          echo "EC2_PUBLIC_IP=${EC2_PUBLIC_IP}" >> $GITHUB_ENV

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          echo "[aws]" > hosts.ini
          echo "${{ env.EC2_PUBLIC_IP }}" >> hosts.ini
          echo "[aws:vars]" >> hosts.ini
          echo "ansible_user=ec2-user" >> hosts.ini
          echo "ansible_ssh_private_key_file=ca1.pem" >> hosts.ini

          ansible-playbook -i hosts.ini setupdocker.yml
